## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [2]:
import numpy as np
arr_1d=np.arange(12)
arr_2d=arr_1d.reshape(2,6)
arr_3d=arr_2d.reshape(2,3,2)

print(arr_1d,'\n',arr_2d,'\n',arr_3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [ ]:
import numpy as np
arr_1d=np.arange(12)
arr_2d=arr_1d.reshape(2,-1)
arr_3d=arr_1d.reshape(-1,3,2)
print("from 1D Arr\n",arr_1d,'\n',arr_2d,'\n',arr_3d,'\n')
arr_1d2=arr_2d.reshape(-1)
arr_3d2=arr_2d.reshape(-1,2,3)
print("from 2D Arr\n",arr_1d2,'\n',arr_3d2,'\n')
arr_1d3=arr_3d.reshape(-1)
arr_2d3=arr_3d.reshape(-1,2)
print("from 3D Arr\n",arr_1d3,'\n',arr_2d3,'\n')

from 1D Arr
 [ 0  1  2  3  4  5  6  7  8  9 10 11] 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

from 2D Arr
 [ 0  1  2  3  4  5  6  7  8  9 10 11] 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 

from 3D Arr
 [ 0  1  2  3  4  5  6  7  8  9 10 11] 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 



Q3. Q1 1차원 배열을 실수형으로 변환

In [ ]:
arr_f=np.arange(12).astype(float)
print(arr_f)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


Q4. Q1 1차원 배열의 dtype을 확인

In [ ]:
arr=np.arange(12)
print(arr.dtype)

int64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [ ]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
arr_2=np.where(arr<0,0,arr)
print(arr_2)


[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [ ]:
arr=np.arange(101)
print(arr[arr%3==0])

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [ ]:
arr=np.arange(101)
print(arr[(arr%3==0) & (arr%5==0)])

[ 0 15 30 45 60 75 90]


Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [ ]:
arr=np.arange(101)
print(arr[(arr%3==0) | (arr%5==0)])

[  0   3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36
  39  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75
  78  80  81  84  85  87  90  93  95  96  99 100]


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [ ]:
random_fields = np.random.randint(101, 151, size=(2,5))
print(random_fields)
Transposed=random_fields.T
print(Transposed)
#print(np.transpose(random_fields))

[[141 142 133 147 103]
 [120 105 101 117 145]]
[[141 120]
 [142 105]
 [133 101]
 [147 117]
 [103 145]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [ ]:
random_fields = np.random.randn(5,5)
print(random_fields)

[[-0.49731498  0.7911119   0.11253578  0.10493481  1.42729918]
 [-1.31141538 -0.28488848  0.04825561  0.16249691 -0.51709262]
 [ 0.43951752 -0.20863325 -1.33308602  0.16672622  0.37441814]
 [-0.52500356 -0.58532733 -1.85422482 -1.08993625  0.69884747]
 [ 0.81110899  1.53146949  0.01727961  0.52076547 -1.95676763]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [5]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array.flatten())
print(original_array.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
arr_view=arr[0]
print(arr_view,'\n')
# view 수정
arr_view[0]=100

print(arr_view,'\n\n',arr)

[1 2 3] 

[100   2   3] 

 [[100   2   3]
 [  4   5   6]]


[링크 텍스트](https://)Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(original_array, '\n')

# 첫 번째 2차원 배열에 대한 view 생성
view_arr = original_array[0]
print(view_arr, '\n')
# view_array를 수정하여 원본 배열에 반영
view_arr[0, 0] = 100

# 출력
print(view_arr, '\n\n', original_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[1 2 3]
 [4 5 6]] 

[[100   2   3]
 [  4   5   6]] 

 [[[100   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array, '\n')

# 2차원 배열을 1차원 배열로 reshape
view_arr = original_array.reshape(-1)
print(view_arr, '\n')
# view_array를 수정하여 원본 배열에 반영
view_arr[0] = 100
print(view_arr, '\n\n', original_array)

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[100   2   3   4   5   6] 

 [[100   2   3]
 [  4   5   6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [ ]:
arr=np.ones((10,10))
print(arr,'\n')
arr[1:9,1:9]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [ ]:
result = np.empty((10, 10), dtype=int)
for i in range(10):
    if i % 2 == 0:
        result[i] = np.arange(1 + 10*i, 11 + 10*i)
    else:
        result[i] = np.arange(10 + 10*i, 0 + 10*i, -1)

print(result)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [ ]:
result = np.zeros((9, 9))
result[2:7, 2:7] = 1
print(result)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [8]:
#### 추가 답안
arr=np.ones((5,5))
## 좌우/상하 padding
padded=np.pad(arr, pad_width=2, mode='constant', constant_values=0)
print(padded)

## Asymmetric Padding
## 위로 1행, 아래로 2행, 왼쪽 3열, 오른쪽 4열 padding 추가
padded=np.pad(arr, ((1,2), (3,4)), mode='constant', constant_values=0)
print(padded)


[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [22]:
# Corrected Ans
ref = np.arange(4)
print(np.diag(ref,k=-1),'\n')
print(np.diag(ref+1,k=-1),'\n')

print(np.diag(ref,k=1),'\n')
print(np.diag(ref+1,k=1),'\n')



#################### Other functions
########### EYEs
print("EYEs\n")
## 2 by 2 행렬, 시작위치 0
print(np.eye(N=2),'\n')

## 2 by 3 행렬, 시작위치 0
print(np.eye(N=2,M=3),'\n')

## 7 by 7 행렬, 시작위치 +2
print(np.eye(7,k=2),'\n')

########### Identify ==  정사각의 EYE
print("Identify\n")
print(np.identity(7),'\n')

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]] 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]] 

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]] 

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]] 

EYEs

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]] 

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

Identify

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]] 



Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [23]:
arr = np.zeros((8, 8), dtype=int)
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
pattern = np.array([[0, 1], [1, 0]])
arr = np.tile(pattern, (4, 4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.


In [3]:
arr=np.arange(336).reshape(6,7,8)
print(arr)
print(np.where(arr==99))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [4]:
arr = np.arange(336).reshape(6, 7, 8)
index_3d = np.unravel_index(99, arr.shape)
print(index_3d)

(1, 5, 3)
