## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

 ## 기초연산


In [ ]:
import pandas as pd
st1=pd.Series({'국어':100, '영어':80, '수학':90})
st2=pd.Series({'수학':80, '국어':90, '영어':90})
print(st1,'\n')
print(st1, '\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    90
dtype: int64


In [ ]:
## 연산
pd.DataFrame(st1+st2)

0
국어  190
수학  170
영어  170

In [ ]:
# 두 학생의 과목별 점수로 사칙 연산 수행
add=st1+st2
sub=st1-st2
mul=st1*st2
div=round((st1/st2), 2)
df=pd.concat([add, sub,mul,div], axis=1)
print(df)

      0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  170 -10  7200  0.89


In [ ]:
df.columns=['덧셈', '뺄셈','곱','나눗셈']
df

덧셈  뺄셈     곱   나눗셈
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  170 -10  7200  0.89

In [ ]:
print(type(add))

<class 'pandas.core.series.Series'>


In [ ]:
df=pd.DataFrame([add, sub,mul,div], index=['덧셈', '뺄셈','곱','나눗셈'])
df[:]

국어       수학       영어
덧셈    190.00   170.00   170.00
뺄셈     10.00    10.00   -10.00
곱    9000.00  7200.00  7200.00
나눗셈     1.11     1.12     0.89

In [ ]:
import numpy as np
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [ ]:
## Q. Null 값을 0으로 변경하여 출력
result.fillna(0, inplace=True)
result

국어       수학   영어
덧셈   0.0   170.00  0.0
뺄셈   0.0    10.00  0.0
곱셈   0.0  7200.00  0.0
나눗셈  0.0     1.12  0.0

In [ ]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

ad=st1.add(st2, fill_value=0)
su=st1.sub(st2, fill_value=0)
mu=st1.mul(st2, fill_value=0)
di=st1.div(st2, fill_value=0)

df=pd.DataFrame([ad, su, mu, di], index=['덧셈','뺄셈','곱셈','나눗셈'])
df

국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [ ]:
np.arange(12.).reshape((3,4))
df1=pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df1


df2=pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.loc[1,'b']=np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [ ]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
# 계산 인자를 뒤집어서 계산
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
print(df1)
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [ ]:
np.arange(12.)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
## 배열의 연산
arr=np.arange(12).reshape(3,4)
print(arr)
arr[0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [ ]:
## broadcasting
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [ ]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series=frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a=np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a=np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
# Task1_0528. 연산메소드 이용 및 NaN 값을 0으로 대체 후 사칙연산을 수행한 후 결과를 출력하세요.
import numpy as np
import pandas as pd

SR1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
SR2 = pd.Series({'수학':80,'한국사':None, '과학': 70})
SR3 = pd.Series({'국사':72,'수학':65,'문학':69, '영어': 30})

ADD=SR1.add(SR2, SR3, fill_value=0)
SUB=SR1.sub(SR2, SR3, fill_value=0)
MUL=SR1.mul(SR2, SR3, fill_value=0)
DIV=SR1.div(SR2, SR3, fill_value=0)
df=pd.DataFrame([ADD,SUB,MUL,DIV], index=['덧셈','뺄셈','곱셈','나눗셈'])
df.fillna(0, inplace=True)
df

과학   국어        수학    영어  한국사
덧셈   70.0  0.0   170.000  80.0  0.0
뺄셈  -70.0  0.0    10.000  80.0  0.0
곱셈    0.0  0.0  7200.000   0.0  0.0
나눗셈   0.0  0.0     1.125   inf  0.0

In [ ]:
# Task2_0528. 주어진 DataFrame의 N열에서 Series s값을 빼고 결과를 새로운 열 O에 저장 후 출력하세요.
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "M": [15, 25, 35, 45, 55],
    "N": [100, 200, 300, 400, 500]
})

print(df,'\n')
# Series 생성
s = pd.Series([5, 10, 15, 20, 25])
SR_new=df.loc[:,'N']-s
SR_new=df['N']-s
df['O']=SR_new

df

    M    N
0  15  100
1  25  200
2  35  300
3  45  400
4  55  500 



M    N    O
0  15  100   95
1  25  200  190
2  35  300  285
3  45  400  380
4  55  500  475

In [ ]:
# Task3_0528. 주어진 DataFrame의 여러 열에 대해 각기 다른 Series를 더하고, 결과를 새로운 DataFrame으로 반환한 후 각 행의 합계를 계산하여 새로운 열에 추가하여 출력하세요.
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [1, 2, 3, 4, 5],
    "B": [10, 20, 30, 40, 50],
    "C": [100, 200, 300, 400, 500]
})

# Series 생성
s1 = pd.Series([5, 5, 5, 5, 5])
s2 = pd.Series([10, 10, 10, 10, 10])
s3 = pd.Series([15, 15, 15, 15, 15])

df_new=df.copy()
df_new['A']=df['A']+s1
df_new['B']=df['B']+s2
df_new['C']=df['C']+s3

df_new['D']=df_new.sum(axis=1)
df_new

A   B    C    D
0   6  20  115  141
1   7  30  215  252
2   8  40  315  363
3   9  50  415  474
4  10  60  515  585

In [ ]:
# Task4_0528. df에서 세 열의 값을 더하여 새로운 컬럼을 생성한 후 출력하세요.
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [10, 20, 30, 40, 50],
    "B": [1, 2, 3, 4, 5],
    "C": [5, 10, 15, 20, 25],
    "D": [3, 6, 9, 12, 15],
    "E": [2, 4, 6, 8, 10]
})
df['F']=df[['A','C','E']].sum(axis=1)
df['F']=df['A']+df['C']+df['E']
df

A  B   C   D   E   F
0  10  1   5   3   2  17
1  20  2  10   6   4  34
2  30  3  15   9   6  51
3  40  4  20  12   8  68
4  50  5  25  15  10  85

In [ ]:
# Task5_0528. df에서 세 열의 값을 평균하여 새로운 컬럼을 생성 후 출력하세요.
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [100, 200, 300, 400, 500],
    "B": [10, 20, 30, 40, 50],
    "C": [1, 2, 3, 4, 5],
    "D": [7, 8, 9, 10, 11],
    "E": [3, 6, 9, 12, 15]
})

df['F']=df[['A','C','E']].mean(axis=1)
df

A   B  C   D   E           F
0  100  10  1   7   3   34.666667
1  200  20  2   8   6   69.333333
2  300  30  3   9   9  104.000000
3  400  40  4  10  12  138.666667
4  500  50  5  11  15  173.333333

In [ ]:
# Task6_0528. df에서 두 개의 열을 더한 값이 다른 한 개의 열보다 큰 경우에는 1, 작은 경우에는 0으로 값을 정하는 새로운 열을 생성한 후 출력하세요.
import pandas as pd

# 데이터프레임 생성
df = pd.DataFrame({
    "A": [2, 3, 4, 5, 6],
    "B": [1, 2, 3, 4, 5],
    "C": [3, 4, 5, 6, 7],
    "D": [8, 9, 10, 11, 12],
    "E": [10, 20, 30, 40, 50]
})

df['F'] = (df['A'] + df['B'] > df['C']).astype(int)
df

A  B  C   D   E  F
0  2  1  3   8  10  0
1  3  2  4   9  20  1
2  4  3  5  10  30  1
3  5  4  6  11  40  1
4  6  5  7  12  50  1

In [1]:
false_as_int=int(False)
true_as_int=int(True)
print(false_as_int)
print(true_as_int)

0
1


In [2]:
print(bool(1))
print(bool(0))

True
False


#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [3]:
import pandas as pd
import seaborn as sns

# Titanic 데이터셋에서 age, sex, 등 5개 열을 선택하여 데이터 프레임 만들기
titanic = sns.load_dataset('titanic')
#df=titanic.loc[:, ['age', 'sex', 'class', 'fare', 'survived']]
df=titanic[['age', 'sex', 'class', 'fare', 'survived']]
print('승객 수:', len(df))
print(df.head())

승객 수: 891
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


In [4]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [6]:
df1=df[['age', 'fare', 'survived','class']]
grouped=df1.groupby(['class'])
print(grouped)

In [8]:
for key,group in grouped:
  print('* key:',key)
  print("* number: ", len(group))
  print(group)
  #print(group.head())


* key: ('First',)
* number:  216
      age     fare  survived  class
1    38.0  71.2833         1  First
3    35.0  53.1000         1  First
6    54.0  51.8625         0  First
11   58.0  26.5500         1  First
23   28.0  35.5000         1  First
..    ...      ...       ...    ...
871  47.0  52.5542         1  First
872  33.0   5.0000         0  First
879  56.0  83.1583         1  First
887  19.0  30.0000         1  First
889  26.0  30.0000         1  First

[216 rows x 4 columns]
* key: ('Second',)
* number:  184
      age     fare  survived   class
9    14.0  30.0708         1  Second
15   55.0  16.0000         1  Second
17    NaN  13.0000         1  Second
20   35.0  26.0000         0  Second
21   34.0  13.0000         1  Second
..    ...      ...       ...     ...
866  27.0  13.8583         1  Second
874  28.0  24.0000         1  Second
880  25.0  26.0000         1  Second
883  28.0  10.5000         0  Second
886  27.0  13.0000         0  Second

[184 rows x 4 columns]
* key: ('

In [10]:
# 연산 메서드 적용
average=grouped.mean()
print(average)
stat=grouped.max()
print(stat)

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363
         age      fare  survived
class                           
First   80.0  512.3292         1
Second  70.0   73.5000         1
Third   74.0   69.5500         1


In [11]:
## 개별 그룹 선택하기
group3=grouped.get_group('Third')
print(group3.head())

    age     fare  survived  class
0  22.0   7.2500         0  Third
2  26.0   7.9250         1  Third
4  35.0   8.0500         0  Third
5   NaN   8.4583         0  Third
7   2.0  21.0750         0  Third


In [12]:
group3.describe()

age        fare    survived
count  355.000000  491.000000  491.000000
mean    25.140620   13.675550    0.242363
std     12.495398   11.778142    0.428949
min      0.420000    0.000000    0.000000
25%     18.000000    7.750000    0.000000
50%     24.000000    8.050000    0.000000
75%     32.000000   15.500000    0.000000
max     74.000000   69.550000    1.000000

In [14]:
# 클래스 열, sex열을 기준으로 분할 (여러열을 기준으로 분할)
df2=df[['age', 'sex', 'class', 'fare', 'survived']]
grouped_2=df2.groupby(['class','sex'])

In [16]:
for key,group in grouped_2:
  print('* key:',key)
  print("* number: ", len(group))
  #print(group)
  print(group.head())

* key: ('First', 'female')
* number:  94
     age     sex  class      fare  survived
1   38.0  female  First   71.2833         1
3   35.0  female  First   53.1000         1
11  58.0  female  First   26.5500         1
31   NaN  female  First  146.5208         1
52  49.0  female  First   76.7292         1
* key: ('First', 'male')
* number:  122
     age   sex  class      fare  survived
6   54.0  male  First   51.8625         0
23  28.0  male  First   35.5000         1
27  19.0  male  First  263.0000         0
30  40.0  male  First   27.7208         0
34  28.0  male  First   82.1708         0
* key: ('Second', 'female')
* number:  76
     age     sex   class     fare  survived
9   14.0  female  Second  30.0708         1
15  55.0  female  Second  16.0000         1
41  27.0  female  Second  21.0000         0
43   3.0  female  Second  41.5792         1
53  29.0  female  Second  26.0000         1
* key: ('Second', 'male')
* number:  108
     age   sex   class  fare  survived
17   NaN  male  S

In [18]:
# 연산 메서드 적용
average=grouped_2.mean()
print(average)
stat=grouped_2.max()
print(stat)
cnt=grouped_2.count()

                     age        fare  survived
class  sex                                    
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447
                age      fare  survived
class  sex                             
First  female  63.0  512.3292         1
       male    80.0  512.3292         1
Second female  57.0   65.0000         1
       male    70.0   73.5000         1
Third  female  63.0   69.5500         1
       male    74.0   69.5500         1
               age  fare  survived
class  sex                        
First  female   85    94        94
       male    101   122       122
Second female   74    76        76
       male     99   108       108
Third  female  102   144       144
       male    253   347       347


데이터 집계(agg),
- 집계 연산을 처리하는 사용자 정의 함수를 그룹 객체에 적용하려면 agg() 메서드 사용
- 모든열에 여러 함수를 매핑 : group객체.agg([함수1,함수2,함수3,…])
- 각 열마다 다른 함수를 매핑 : group객체.agg({‘열1’: 함수1, ‘열2’:함수2, …})

변환(transform)
- 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
- 데이터 변환 연산 : group객체.transform(매핑함수)

필터링(filter)
- 그룹 객체에 filter() 메서드를 적용할 때 조건식을 가진 함수를 전달하면 조건이 참인 그룹만을 남김
- 그룹 객체 필터링 : group 객체.filter(조건 함수식)

객체에 함수 매핑(apply)
 - 판다스 객체의 개별 원소를 특정 함수에 일대일로 매핑. 사용자가 원하는 대부분의 연산을 그룹 객체에 적용
 - group 객체.apply(매핑함수)

In [19]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])

In [20]:
mean_all=grouped.mean()
print(mean_all, "\n")
print(type(mean_all))

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363 

<class 'pandas.core.frame.DataFrame'>


In [23]:
mean_all.index.name=None
print(mean_all, "\n")

              age       fare  survived
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363 



In [24]:
## 모든 열의 표준편차를 집계하여 DF로 반환
std_all=grouped.std()
print(std_all, "\n")
print(type(std_all))

              age       fare  survived
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949 

<class 'pandas.core.frame.DataFrame'>


In [27]:
# 각 그룹에 대한 fare 열의 표준 편차를 집계하여 시리즈로 반환
std_fare=grouped.fare.std()
print(std_fare, "\n", type(std_fare))

First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64 
 <class 'pandas.core.series.Series'>


In [28]:
# 그룹 객체에 agg() 메서드를 적용 - 사용자 정의 함수를 인수로 전달
def min_max(x):       ## 최대값 - 최소값 SPAN
  return x.max() - x.min()

# 각 그룹의 최대값과 최소값의 차이를 계산하여 그룹별로 집계
agg_minmax=grouped.agg(min_max)
print(agg_minmax.head())


          age      fare  survived
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1


In [31]:
# 모든열에 여러 함수를 매핑: group객체. agg([함수1, 함수2, 함수3,...])
# 각 열마다 다른 함수를 매핑: group객체.agg({'열1':함수1, '열2':함수2,...})

# 모든열에 여러 함수를 매핑: group객체. agg([함수1, 함수2, 함수3,...])
agg_all=grouped.agg(['min','max','mean',min_max])
print(agg_all.head())

         age                          fare                                 \
         min   max       mean min_max  min       max       mean   min_max   
First   0.92  80.0  38.233441   79.08  0.0  512.3292  84.154687  512.3292   
Second  0.67  70.0  29.877630   69.33  0.0   73.5000  20.662183   73.5000   
Third   0.42  74.0  25.140620   73.58  0.0   69.5500  13.675550   69.5500   

       survived                        
            min max      mean min_max  
First         0   1  0.629630       1  
Second        0   1  0.472826       1  
Third         0   1  0.242363       1  


In [37]:
# 각 열마다 다른 함수를 매핑: group객체.agg({'열1':함수1, '열2':함수2,...})
agg_sep=grouped.agg({'age':'min','fare':['min','max', min_max],'survived':'mean'})
print(agg_sep.head())

         age fare                      survived
         min  min       max   min_max      mean
First   0.92  0.0  512.3292  512.3292  0.629630
Second  0.67  0.0   73.5000   73.5000  0.472826
Third   0.42  0.0   69.5500   69.5500  0.242363


In [40]:
import pandas as pd
import seaborn as sns

# Titanic 데이터셋에서 age, sex, 등 5개 열을 선택하여 데이터 프레임 만들기
titanic = sns.load_dataset('titanic')
#df=titanic.loc[:, ['age', 'sex', 'class', 'fare', 'survived']]
df=titanic[['age', 'sex', 'class', 'fare', 'survived']]
grouped=df.groupby(['class'])

In [42]:
## 데이터 개수가 200개 이상인 그룹만을 필터링하여 DF로 반환
grouped_f=grouped.filter(lambda x:len(x)>=200)
print(grouped_f, '\n', type(grouped_f))

      age     sex  class     fare  survived
0    22.0    male  Third   7.2500         0
1    38.0  female  First  71.2833         1
2    26.0  female  Third   7.9250         1
3    35.0  female  First  53.1000         1
4    35.0    male  Third   8.0500         0
..    ...     ...    ...      ...       ...
885  39.0  female  Third  29.1250         0
887  19.0  female  First  30.0000         1
888   NaN  female  Third  23.4500         0
889  26.0    male  First  30.0000         1
890  32.0    male  Third   7.7500         0

[707 rows x 5 columns] 
 <class 'pandas.core.frame.DataFrame'>


In [43]:
grouped_f.value_counts('class')

class
Third     491
First     216
Second      0
Name: count, dtype: int64

In [44]:
df.value_counts('class')

class
Third     491
First     216
Second    184
Name: count, dtype: int64

#### 함수 매핑
커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map 함수는 Series의 각 요소에 함수를 적용.
- apply 함수는 Series 또는 DataFrame의 행이나 열에 함수를 적용.
- applymap 함수는 DataFrame의 각 요소에 함수를 적용.

In [70]:
import pandas as pd
s=pd.Series([1,2,3,4,5])

s_mapped=s.map(lambda x: x+2)
print(s_mapped)

0    3
1    4
2    5
3    6
4    7
dtype: int64


In [73]:
## DATAFRAME에 mapping 적용

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

print(df.head())
# 각 열에 대해 최대값을 구하는 함수
df_ap_col=df.apply(lambda x: x.max(), axis=0)
print(df_ap_col)
# 각 행에 대해 합계를 구하는 함수
df_ap_row=df.apply(lambda x: x.sum(), axis=1)
print(df_ap_row)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
A    3
B    6
C    9
dtype: int64
0    12
1    15
2    18
dtype: int64


In [74]:
## applymap은 DATAFRAME에만 적용되며, 각 요소에 함수를 적용

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 각 열에 2를 더하는 함수
df_apmap=df.applymap(lambda x: x+2)
print(df_apmap)

   A  B   C
0  3  6   9
1  4  7  10
2  5  8  11


In [92]:
import pandas as pd
import numpy as np
import random

np.random.seed(10)
# 함수 적용과 매핑
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037

In [81]:
format =lambda x: '%.2f' %x
# map함수는 SR에만 적용
frame['e'].map(format)

Utah       2.23
Ohio       0.83
Texas     -0.82
Oregon    -0.31
Name: e, dtype: object

In [85]:
f=lambda x: x.max()-x.min()
frame.apply(f)

b    2.101369
d    1.003332
e    3.053308
dtype: float64

In [86]:
frame.apply(f,axis=1)

Utah      2.401414
Ohio      0.567770
Texas     1.933355
Oregon    0.862823
dtype: float64

In [87]:
frame.apply(f,axis='columns')

Utah      2.401414
Ohio      0.567770
Texas     1.933355
Oregon    0.862823
dtype: float64

In [88]:
f1=lambda x: round(x*10)
frame.apply(f1, axis=0)

b    d     e
Utah    -1.0 -2.0  22.0
Ohio     3.0  4.0   8.0
Texas   11.0  8.0  -8.0
Oregon -10.0 -1.0  -3.0

In [90]:
f1=lambda x: round(x*10)
frame.apply(f1, axis=1)

b    d     e
Utah    -1.0 -2.0  22.0
Ohio     3.0  4.0   8.0
Texas   11.0  8.0  -8.0
Oregon -10.0 -1.0  -3.0

In [93]:
f1=lambda x: sum(x)
frame.apply(f1, axis=0)

b    1.414114
d    1.878190
e   -1.058157
dtype: float64

In [95]:
## 여러값을 가진 series 반환
print(frame); print()
def f(x):
  return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

               b         d         e
Utah    1.331587  0.715279 -1.545400
Ohio   -0.008384  0.621336 -0.720086
Texas   0.265512  0.108549  0.004291
Oregon -0.174600  0.433026  1.203037



b         d         e
min -0.174600  0.108549 -1.545400
max  1.331587  0.715279  1.203037

In [96]:
format =lambda x: '%.2f' %x

frame.applymap(format)

b     d      e
Utah     1.33  0.72  -1.55
Ohio    -0.01  0.62  -0.72
Texas    0.27  0.11   0.00
Oregon  -0.17  0.43   1.20

In [103]:
np.random.seed(0)
data=np.random.randint(1,100, size=(5,5))
df=pd.DataFrame(data,columns=list('abcde'))
df['f']=df.apply(lambda x: x.sum(), axis=1)
#df['f']=df.apply(lambda x: x.a+x.b+x.c+x.d+x.e,axis=1)
df

a   b   c   d   e    f
0  45  48  65  68  68  294
1  10  84  22  37  88  241
2  71  89  89  13  59  321
3  66  40  88  47  89  330
4  82  38  26  78  73  297

In [109]:
## 표준화: 데이터의 평균을 0, 표준편차를 1로 변환하는 과정,
## 이 과정을 통해 데이터의 scale을 조정하고 비교 가능한 형태로 만듬
# Transform: 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
# 데이터 변환 연산 : group객체.transform(매핑함수)


def z_score(x):
  return (x-x.mean())/x.std()
df_z=df.a.transform(z_score)
print(df_z, type(df_z))

0   -0.344827
1   -1.576351
2    0.570020
3    0.394088
4    0.957070
Name: a, dtype: float64 <class 'pandas.core.series.Series'>


In [110]:
def z_score(x):
  return (x-x.mean())/x.std()
df_z=df.apply(z_score)
df_z=df.apply(lambda x: z_score(x))
df_z

a         b         c         d         e         f
0 -0.344827 -0.477299  0.215257  0.754401 -0.570413 -0.074984
1 -1.576351  0.978867 -1.107037 -0.451085  0.971244 -1.603498
2  0.570020  1.181112  0.953282 -1.384365 -1.264159  0.703693
3  0.394088 -0.800891  0.922531 -0.062219  1.048327  0.963252
4  0.957070 -0.881789 -0.984033  1.143268 -0.184999  0.011536